package.json - Import "slick", required for browserify and juice
Running `grunt build` fails with an error (below). Loading `slick` resolves the error.

```
...
Running "browserify:debug" (browserify) task
>> Error: Cannot find module 'slick' from '/Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico-upstream/bower_components/juice/lib'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```